version: "3.8"
services:
  nodeserver:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./app:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  databaseserver:
    image: "mongo:4"
  